name: xview3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - rasterio
  - Shapely
  - pip
  - pip:
    - torch==2.8.0
    - torchvision==0.23.0
    - pyproj==3.5.0
    - Fire==0.5.0
    - pandas==1.5.3
    - scikit-image==0.19.3
    - scikit-learn==1.2.2
    - tifffile==2020.8.25
    - albumentations==1.3.1
    - hydra-core==1.3.2
    - timm==0.9.7
    - torch-optimizer==0.3.0
    - numpy==1.23.5
    - rasterio==1.3.0
    - git+https://github.com/BloodAxe/pytorch-toolbelt@e52fbed6cca16151423c4ae396256308696dfc8f
    - git+https://github.com/SamerKharboush/catalyst-python3.11.git@f7f5c0752756d54d041e222e99643af0d1c4c625
    - -f https://download.pytorch.org/whl/cu128
